interface CompanyData {
  value: string;
  unrestricted_value: string;
  data: {
    kpp: string;
    kpp_largest: string | null;
    capital: string | null;
    invalid: string | null;
    management: {
      name: string;
      post: string;
      start_date: number;
      disqualified: string | null;
    };
    founders: string | null;
    managers: string | null;
    predecessors: string | null;
    successors: string | null;
    branch_type: string;
    branch_count: number;
    source: string | null;
    qc: string | null;
    hid: string;
    type: string;
    state: {
      status: string;
      code: string | null;
      actuality_date: number;
      registration_date: number;
      liquidation_date: string | null;
    };
    opf: {
      type: string;
      code: string;
      full: string;
      short: string;
    };
    name: {
      full_with_opf: string;
      short_with_opf: string;
      latin: string | null;
      full: string;
      short: string;
    };
    inn: string;
    ogrn: string;
    okpo: string;
    okato: string;
    oktmo: string;
    okogu: string;
    okfs: string;
    okved: string;
    okveds: string | null;
    authorities: string | null;
    documents: string | null;
    licenses: string | null;
    finance: {
      tax_system: string | null;
      income: string | null;
      expense: string | null;
      revenue: string | null;
      debt: string | null;
      penalty: string | null;
      year: number | null;
    };
    address: {
      value: string;
      unrestricted_value: string;
      invalidity: string | null;
      data: {
        postal_code: string;
        country: string;
        country_iso_code: string;
        federal_district: string;
        region_fias_id: string;
        region_kladr_id: string;
        region_iso_code: string;
        region_with_type: string;
        region_type: string;
        region_type_full: string;
        region: string;
        area_fias_id: string | null;
        area_kladr_id: string | null;
        area_with_type: string | null;
        area_type: string | null;
        area_type_full: string | null;
        area: string | null;
        city_fias_id: string;
        city_kladr_id: string;
        city_with_type: string;
        city_type: string;
        city_type_full: string;
        city: string;
        city_area: string;
        city_district_fias_id: string | null;
        city_district_kladr_id: string | null;
        city_district_with_type: string;
        city_district_type: string;
        city_district_type_full: string;
        city_district: string;
        settlement_fias_id: string | null;
        settlement_kladr_id: string | null;
        settlement_with_type: string | null;
        settlement_type: string | null;
        settlement_type_full: string | null;
        settlement: string | null;
        street_fias_id: string;
        street_kladr_id: string;
        street_with_type: string;
        street_type: string;
        street_type_full: string;
        street: string;
        stead_fias_id: string | null;
        stead_cadnum: string | null;
        stead_type: string | null;
        stead_type_full: string | null;
        stead: string | null;
        house_fias_id: string;
        house_kladr_id: string;
        house_cadnum: string;
        house_flat_count: string | null;
        house_type: string;
        house_type_full: string;
        house: string;
        block_type: string;
        block_type_full: string;
        block: string;
        entrance: string | null;
        floor: string | null;
        flat_fias_id: string | null;
        flat_cadnum: string | null;
        flat_type: string;
        flat_type_full: string;
        flat: string;
        flat_area: string;
        square_meter_price: string;
        flat_price: string | null;
        room_fias_id: string | null;
        room_cadnum: string | null;
        room_type: string | null;
        room_type_full: string | null;
        room: string | null;
        postal_box: string | null;
        fias_id: string;
        fias_code: string;
        fias_level: string;
        fias_actuality_state: string;
        kladr_id: string;
        geoname_id: string;
        capital_marker: string;
        okato: string;
        oktmo: string;
        tax_office: string;
        tax_office_legal: string;
        timezone: string;
        geo_lat: string;
        geo_lon: string;
        beltway_hit: string;
        beltway_distance: string | null;
        metro: {
          name: string;
          line: string;
          distance: number;
        }[];
        divisions: string | null;
        qc_geo: string;
        qc_complete: string | null;
        qc_house: string | null;
        history_values: string | null;
        unparsed_parts: string | null;
        source: string;
        qc: string;
      };
    };
    phones: string | null;
    emails: string | null;
    ogrn_date: number;
    okved_type: string;
    employee_count: string | null;
  };
}

export default CompanyData;